#include "asm_x86_64.h"

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static char *duplicate(const char *value) {
  const size_t length = strlen(value);
  char *copy = malloc(length + 1U);
  if (copy == NULL) return NULL;
  memcpy(copy, value, length + 1U);
  return copy;
}

static int append(char **text, size_t *length, size_t *capacity,
                  const char *format, ...) {
  va_list arguments;
  va_start(arguments, format);
  va_list copy;
  va_copy(copy, arguments);
  const int required = vsnprintf(NULL, 0U, format, copy);
  va_end(copy);
  if (required < 0) {
    va_end(arguments);
    return 0;
  }
  const size_t needed = *length + (size_t)required + 1U;
  if (needed > *capacity) {
    size_t next_capacity = *capacity == 0U ? 1024U : *capacity;
    while (next_capacity < needed) next_capacity *= 2U;
    char *next = realloc(*text, next_capacity);
    if (next == NULL) {
      va_end(arguments);
      return 0;
    }
    *text = next;
    *capacity = next_capacity;
  }
  (void)vsnprintf(*text + *length, *capacity - *length, format, arguments);
  va_end(arguments);
  *length += (size_t)required;
  return 1;
}

static int diagnostic(CAssemblyResult *result, const char *message) {
  char **items = realloc(result->diagnostics,
                         (result->diagnostic_count + 1U) * sizeof(*items));
  if (items == NULL) return 0;
  result->diagnostics = items;
  result->diagnostics[result->diagnostic_count] = duplicate(message);
  if (result->diagnostics[result->diagnostic_count] == NULL) return 0;
  result->diagnostic_count++;
  return 1;
}

static int slot_for(const CSemanticResult *semantic, const char *name) {
  for (size_t index = 0U; index < semantic->count; index++) {
    if (strcmp(semantic->items[index].name, name) == 0) {
      return (int)((index + 1U) * 8U);
    }
  }
  return 0;
}

static int emit_expression(const CAstNode *node, const CSemanticResult *semantic,
                           char **text, size_t *length, size_t *capacity) {
  if (node == NULL) return 0;
  if (node->kind == C_AST_LITERAL) {
    if (node->data.literal.literal_kind != C_TOKEN_INTEGER) return 0;
    return append(text, length, capacity, "    mov rax, %s\n",
                  node->data.literal.value);
  }
  if (node->kind == C_AST_VARIABLE_REFERENCE) {
    const int slot = slot_for(semantic, node->data.reference.name);
    return slot > 0 && append(text, length, capacity,
                              "    mov rax, [rbp-%d]\n", slot);
  }
  if (node->kind == C_AST_BINARY) {
    if (!emit_expression(node->data.binary.left, semantic, text, length,
                         capacity) ||
        !append(text, length, capacity, "    push rax\n") ||
        !emit_expression(node->data.binary.right, semantic, text, length,
                         capacity) ||
        !append(text, length, capacity, "    mov rcx, rax\n    pop rax\n")) {
      return 0;
    }
    if (strcmp(node->data.binary.operator, "+") == 0) {
      return append(text, length, capacity, "    add rax, rcx\n");
    }
    if (strcmp(node->data.binary.operator, "-") == 0) {
      return append(text, length, capacity, "    sub rax, rcx\n");
    }
    if (strcmp(node->data.binary.operator, "*") == 0) {
      return append(text, length, capacity, "    imul rax, rcx\n");
    }
    if (strcmp(node->data.binary.operator, "/") == 0) {
      return append(text, length, capacity,
                    "    cqo\n    idiv rcx\n");
    }
  }
  return 0;
}

int c_generate_nasm_x86_64(const CAstNode *program,
                           const CSemanticResult *semantic,
                           CAssemblyResult *result) {
  if (program == NULL || semantic == NULL || result == NULL ||
      program->kind != C_AST_PROGRAM) return 0;
  memset(result, 0, sizeof(*result));
  size_t length = 0U;
  size_t capacity = 0U;
  const size_t frame_size = ((semantic->count * 8U) + 15U) & ~15U;
  if (!append(&result->text, &length, &capacity,
              "; generated by arabicc C\n"
              "global main\n"
              "extern printf\n"
              "section .data\n"
              "fmt_int: db \"%%ld\", 10, 0\n"
              "section .text\n"
              "main:\n"
              "    push rbp\n"
              "    mov rbp, rsp\n"
              "    sub rsp, %zu\n", frame_size)) {
    c_assembly_result_free(result);
    return 0;
  }
  for (size_t index = 0U; index < program->data.program.statements.count; index++) {
    const CAstNode *statement = program->data.program.statements.items[index];
    if (statement->kind == C_AST_ASSIGNMENT) {
      if (!emit_expression(statement->data.assignment.expression, semantic,
                           &result->text, &length, &capacity)) {
        (void)diagnostic(result, "تعذر تحويل تعبير الإسناد إلى NASM integer");
        return 1;
      }
      const int slot = slot_for(semantic, statement->data.assignment.name);
      if (slot == 0 || !append(&result->text, &length, &capacity,
                               "    mov [rbp-%d], rax\n", slot)) {
        (void)diagnostic(result, "متغير الإسناد غير موجود في stack layout");
        return 1;
      }
    } else if (statement->kind == C_AST_PRINT) {
      for (size_t value_index = 0U;
           value_index < statement->data.print.values.count; value_index++) {
        if (!emit_expression(statement->data.print.values.items[value_index],
                             semantic, &result->text, &length, &capacity) ||
            !append(&result->text, &length, &capacity,
                    "    mov rsi, rax\n"
                    "    lea rdi, [rel fmt_int]\n"
                    "    xor eax, eax\n"
                    "    call printf\n")) {
          (void)diagnostic(result, "تعذر تحويل print إلى NASM integer");
          return 1;
        }
      }
    } else if (statement->kind != C_AST_EMPTY) {
      (void)diagnostic(result, "تعليمة غير مدعومة في NASM backend الحالي");
      return 1;
    }
  }
  if (!append(&result->text, &length, &capacity,
              "    xor eax, eax\n    leave\n    ret\n"
              "section .note.GNU-stack noalloc noexec nowrite progbits\n")) {
    c_assembly_result_free(result);
    return 0;
  }
  return 1;
}

void c_assembly_result_free(CAssemblyResult *result) {
  if (result == NULL) return;
  free(result->text);
  for (size_t index = 0U; index < result->diagnostic_count; index++) {
    free(result->diagnostics[index]);
  }
  free(result->diagnostics);
  memset(result, 0, sizeof(*result));
}
